USE DATABASE IOT_DB;
USE SCHEMA STG;



COPY INTO STG.STG_THERMOSTAT
FROM @AZURE_IOT_STAGE/IoT_Thermostat.csv
FILE_FORMAT = (FORMAT_NAME = ff_csv_iot)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = CONTINUE;


SELECT * 
FROM STG.STG_FRIDGE; 

CALL STG.load_from_stage('AZURE_IOT_STAGE', 'ff_csv_iot', 'STG.ETL_CONTROL');


SELECT 'FRIDGE' AS src, COUNT(*) AS cnt FROM STG.STG_FRIDGE
UNION ALL
SELECT 'GARAGE_DOOR', COUNT(*) FROM STG.STG_GARAGE_DOOR
UNION ALL
SELECT 'GPS_TRACKER', COUNT(*) FROM STG.STG_GPS_TRACKER
UNION ALL
SELECT 'MODBUS', COUNT(*) FROM STG.STG_MODBUS
UNION ALL
SELECT 'MOTION_LIGHT', COUNT(*) FROM STG.STG_MOTION_LIGHT
UNION ALL
SELECT 'THERMOSTAT', COUNT(*) FROM STG.STG_THERMOSTAT
UNION ALL
SELECT 'WEATHER', COUNT(*) FROM STG.STG_WEATHER;

