version: 2


sources:
  - name: staging
    schema: STG   # your actual schema
    tables:
      - name: STG_FRIDGE
        description: "Raw IoT fridge staging table"
      - name: STG_GARAGE_DOOR
        description: "Raw IoT garage staging table"  

  - name: dwh
    schema: DWH   # your actual schema
    tables:
      - name: DIM_DATE
        description: "Date Dimension"
      - name: DIM_TIME
        description: "Time Dimension" 
      - name: DIM_FRIDGE
        description: "Fridge Dimension" 

