version: 2


sources:
  - name: staging
    schema: STG   # your actual schema
    tables:
      - name: STG_FRIDGE
        description: "Raw IoT fridge staging table"
      - name: STG_GARAGE_DOOR
        description: "Raw IoT garage staging table" 
      - name: STG_GPS_TRACKER
        description: "Raw IoT GPS tracker staging table"
      - name: STG_MODBUS
        description: "Raw IoT Modbus staging table"
      - name: STG_MOTION_LIGHT
        description: "Raw IoT motion light staging table"
      - name: STG_THERMOSTAT
        description: "Raw IoT thermostat staging table"
      - name: STG_WEATHER
        description: "Raw IoT weather sensor staging table"

   

  - name: dwh
    schema: DWH   # your actual schema
    tables:
      - name: DIM_DATE
        description: "Date Dimension"
      - name: DIM_TIME
        description: "Time Dimension" 
      - name: DIM_FRIDGE
        description: "Fridge Dimension" 

