FROM ghcr.io/dbt-labs/dbt-core:1.10.13

# Install Snowflake adapter
RUN pip install dbt-snowflake openlineage-dbt

# Set working directory inside container
WORKDIR /usr/app

# Copy the entire dbt project (so packages.yml is visible during build)
COPY . /usr/app

# Install dbt packages during build
RUN dbt deps

# Default entrypoint
ENTRYPOINT ["dbt"]
