version: 2

models:
  - name: FACT_FRIDGE
    description: "Fact table for fridge temperature readings with links to date, time, and fridge dimensions."
    constraints:
      - type: primary_key
        columns: [FACT_FRIDGE_SR_KEY]
      - type: foreign_key
        name: fk_fridge_date
        columns: [DATE_SR_KEY]
        to: source('dwh','DIM_DATE')
        to_columns: [DATE_SR_KEY]
      - type: foreign_key
        name: fk_fridge_time
        columns: [TIME_SR_KEY]
        to: source('dwh','DIM_TIME')
        to_columns: [TIME_SR_KEY]
      - type: foreign_key
        name: fk_fridge_dim
        columns: [DIM_FRIDGE_SR_KEY]
        to: source('dwh','DIM_FRIDGE')
        to_columns: [DIM_FRIDGE_SR_KEY]

    columns:
      - name: FACT_FRIDGE_SR_KEY
        description: "Surrogate key for the fact row."
        tests:
          - not_null
          - unique

      - name: MAX_FRIDGE_TEMPERATURE
        description: "Temperature in degrees Celsius."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between -50 and 100"
      - name: MIN_FRIDGE_TEMPERATURE
        description: "Temperature in degrees Celsius."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between -50 and 100"
      - name: AVG_FRIDGE_TEMPERATURE
        description: "Temperature in degrees Celsius."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "between -50 and 100"
      - name: DATE_SR_KEY
        description: "Reference to DIM_DATE."
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('dwh','DIM_DATE')
                field: DATE_SR_KEY

      - name: TIME_SR_KEY
        description: "Reference to DIM_TIME."
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('dwh','DIM_TIME')
                field: TIME_SR_KEY

      - name: DIM_FRIDGE_SR_KEY
        description: "Reference to DIM_FRIDGE."
        tests:
          - not_null
          - relationships:
              arguments:
                to: source('dwh','DIM_FRIDGE')
                field: DIM_FRIDGE_SR_KEY

      - name: INSERT_TIME
        description: "Record insert timestamp."

      - name: UPDATE_TIME
        description: "Record update timestamp."
