models:
  - name: DIM_FRIDGE
    description: "Dimension table for fridge IoT metadata"
    columns:
      - name: dim_fridge_sr_key
        description: "Surrogate key for DIM_FRIDGE"
        tests:
          - unique
          - not_null
      - name: label
        description: "Fridge IoT label (device identifier or category)"
      - name: temp_condition
        description: "Temperature condition (e.g., high, low, normal)"
      - name: type
        description: "Type or classification of the IoT fridge device"
        
  - name: DIM_GARAGE_DOOR
    description: "Dimension table for garage door IoT metadata"
    columns:
      - name: dim_garage_door_sr_key
        description: "Surrogate key for DIM_GARAGE_DOOR"
        tests:
          - unique
          - not_null
      - name: door_state
        description: "Door state such as open or closed"
      - name: label
        description: "Device label or identifier"
      - name: sphone_signal
        description: "Signal strength reported by the sensor"
      - name: type
        description: "Device type or classification"