name: Update dbt packages

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dbt-packages:
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-core (temporary just for deps)
        run: pip install dbt-core

      - name: Install dependencies from packages.yml
        run: dbt deps --project-dir dbt

      - name: Commit and push dbt_packages folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dbt/dbt_packages/
          git commit -m "Auto-update dbt packages"
          git push origin main || echo "No changes to commit"
